#!/usr/bin/perl

use strict;
use DBI;
use CGI;


sub get_data
{
    my @args  = @_;
    my $sort = @args[0];
    
    if (defined $sort && $sort ne '') {
		$sort = $sort;
	} else {
		$sort = 'title';
	}
	
    my $dbh = DBI->connect(          
        "dbi:SQLite:dbname=books.db", 
        "",                          
        "",                       
        { RaiseError => 1 },         
    ) or die $DBI::errstr;
    
    my $sth = $dbh->prepare("SELECT title, author, editor, read
                    FROM Books B
                    JOIN Authors A
                    ON B.author_id = A.id
                    JOIN Editors E
                    ON B.editor_id = E.id
                    ORDER BY $sort;");
    $sth->execute();

   
# Printing in a loop
    print "<div align='center'> ";
    print "<table CELLPADDING=2><TR><TH><a href='./livres?sort=title'>Titre</a></TH><TH><a href='./livres?sort=author'>Auteur</a></TH><TH><a href='./livres?sort=editor'>Editeur</a></TH><TH>Lu ?</TH></TR>";
    my $row;
    my $i = 1;
    while ($row = $sth->fetchrow_arrayref())
    {
        my $read;
        if (@$row[4] == 1) {
            $read = "Oui";
        } else {
            $read = "Non";
        }
        
        print " <TR><TD> @$row[0]</TD><TD> @$row[1]</TD><TD> @$row[2]</TD><TD> $read</TD></TR>";
        $i += 1;
    }


    $sth->finish();
    $dbh->disconnect();
    print "</table> </div>";
}


# Actually displaying as html
my $cgi = CGI->new;
print $cgi->header(-type => 'text/html',
                   -charset => 'utf-8');
print $cgi->start_html(-title => "Livres",
                       -bgcolor => "black",
                       -text => "white",
                       -charset=>"UTF-8",
                       -encoding=>"UTF-8");

print  "<style type='text/css'>

        body {
            font-family: verdana ;
            font-size: 100% ;
            text-align: center ;
            background: black ;
            text: white ;
            }

        table {
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid dodgerblue;
        }
        a{
          color:				limegreen;
          font-weight:		italic;
          text-decoration:    none;
            
        } a:hover {
            color:				yellow;	
        } a:active {
            color:				red;
        }


        </style>";
my $sort = $cgi->param("sort");
&get_data($sort);

print $cgi-> end_html;
